export const properties = [
    {
      id: 1,
      title: 'Braetd Girls Hostel ',
      location: 'Kampala, Wandegeya',
      price: 'USD $200 per-3month',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSXa8l3ENQaN6gaM9IqNUhxYLgGd7gV-k0AA&s',
    },
    {
      id: 2,
      title: 'Aryan Hostel',
      location: 'Kampala, Wandegeya',
      price: 'USD $500 per-3month',
      image: 'https://hostels.campusbee.ug/wp-content/uploads/2022/01/IMG-20220126-WA0003-51bafbf4-750x536.jpg',
    },
    {
      id: 3,
      title: 'Olympia Hostel',
      location: 'Kampala, Makerere',
      price: 'USD $450 per-3month',
      image: 'https://hostels.campusbee.ug/wp-content/uploads/2022/01/IMG_20220126_152607-75a4ab50.jpg',
    },
    {
      id: 4,
      title: 'Dream World Hostel',
      location: 'Kampala, Makerere',
      price: 'USD $380 per -3month',
      image: 'https://campusbee.ug/wp-content/uploads/2023/08/mak-hostel.jpg',
    },
    {
      id: 4,
      title: 'Ideal Platinum Hostel',
      location: 'Kampala, Uganda',
      price: 'USD $600 per -3month',
      image: 'https://hostels.campusbee.ug/wp-content/uploads/2022/02/IMG-20220201-WA0026-8a325da3.jpg',
    },
    {
      id: 4,
      title: 'Akamwesi Hostel',
      location: 'Kampala, Nakawa',
      price: 'USD $600 per -3month',
      image: 'https://www.ugabox.com/images/business/directory/hostels/akamwesi-hostel/Akamwesi-Hostel-Nakawa-Aka-Hostel-Makerere-University-Business-School-MUBS-Victoria-University-Student-Hostel-Kampala-Uganda-01.JPG',
    },
    {
      id: 4,
      title: 'Paradise Hostel',
      location: 'Kampala, Kireka',
      price: 'USD $220 per -3month',
      image: 'https://campusbee.ug/wp-content/uploads/2020/01/Paradise-Hostel.jpg',
    },
    {
      id: 4,
      title: 'Premium Hostel',
      location: 'Kampala, UCU Mukono',
      price: 'USD $300 per -3month',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTotnvtXcvPBKApUIAvJeODS2CHyD_fYbVA9s1bwu8v3IoMP3GuhrPXe-mmPmqsZTlKQN0&usqp=CAU',
    },
  ];